name: Deploy React Application
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t rahulshah10/pma_admin_frontend_app_2026 --build-arg VITE_REACT_APP_NODE_ENV='production' --build-arg VITE_API_BASE_SERVER_URL='${{secrets.VITE_API_BASE_SERVER_URL}}' .
      - name: Publish Image to docker hub
        run: docker push rahulshah10/pma_admin_frontend_app_2026:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull rahulshah10/pma_admin_frontend_app_2026:latest

      - name: Delete old container
        run: docker rm -f pma_admin_frontend_app_2026-container || true

      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name pma_admin_frontend_app_2026-container rahulshah10/pma_admin_frontend_app_2026:latest

      - name: Copy React build to /var/www/react-app and reload Nginx
        run: |
          TARGET_DIR="/var/www/react-app"
          CONTAINER_NAME="pma_admin_frontend_app_2026-container"

          # Create target directory if it doesn't exist
          sudo mkdir -p "$TARGET_DIR"

          # Delete existing files if any
          if [ "$(ls -A $TARGET_DIR)" ]; then
            echo "Deleting existing files in $TARGET_DIR..."
            sudo rm -rf "$TARGET_DIR"/*
          fi

          # Copy files from Docker container
          echo "Copying files from container $CONTAINER_NAME..."
          sudo docker cp "$CONTAINER_NAME":/usr/share/nginx/html/. "$TARGET_DIR/"

          # Reload Nginx
          echo "Reloading Nginx..."
          sudo systemctl reload nginx

      - name: Clean up unused Docker images
        run: sudo docker image prune -f
